spring:
  datasource:
    url: jdbc:h2:mem:holdhive;MODE=MySQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

holdhive:
  market:
    external-enabled: false
    cache-ttl: 30d
    http-timeout: 2s
